deployment:
  tasks:
    - export DEPLOYPATH=/home/thelsggl/public_html/
    - /bin/echo "Cleaning deployment directory"
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/echo "Copying SPA files"
    - /bin/cp -R dist/spa/* $DEPLOYPATH/
    - /bin/echo "Deployment complete, listing files:"
    - /bin/ls -la $DEPLOYPATH/